Fix error by replacing method
csc530/resume-builder pull request #3
Opened 2024-07-19 15:17 UTC by smellilac

2024-07-19 20:37 UTC, csc530 requested changes
the experience and description are non-nullable `List<string>` (not `List<string>?` so the `orNull()` should be removed to prevent exceptions.

thanks for the fix, the tests project is quite a mess and have gotten **very** out of sync of the commands😅

2024-07-20 09:26 UTC, smellilac commented
I apologize for my inattention :disappointed_relieved: Removed possible refund null

2024-07-20 15:03 UTC, csc530 approved these changes

2024-07-20 15:04 UTC, csc530 commented
It's all good

2024-07-20 15:04 UTC, merged